### PR TITLE
Fix Power Up Sprites | Add Game Sounds

### LINKED ISSUE #23: Deployment
Deploy the game. Look into https://learn.unity.com/tutorial/how-to-publish-for-webgl

### LINKED ISSUE #24: Add music
- [x] Attack sound effect
- [ ] Background music during gameplay
- [ ] Sound effect after choosing powerup
- [x] Background music during victory
- [x] Music for start screen
- [x] Music for start screen
- [x] Death sound effect
- [x] Spawn sound effect
- [x] Powerup Screen audio

### PR DESCRIPTION
**Pull request by ajwad-shaikh**
Fixes #24 #26

Game Music deemed not necessary at the moment

Improved in-game UI - by @cqvu 

Fixes #23 

AmongUps is now deployed at https://play.unity.com/mg/2d/amongups

### CODE REVIEW

File: Assets/Scripts/Mechanics/GameController.cs [hunk 1]
```diff
@@ -62,12 +62,12 @@ void Update()
             if(impostor.playerScore >= 3) {
                 // declare impostor as Winner
                 victoryScreen.SetActive(true);
-                victoryScreen.transform.GetChild(1).GetComponent<Image>().color = new Color32(255, 243, 0, 255);
+                victoryScreen.transform.GetChild(1).GetComponent<Image>().color = impostor.color;
             }
```
Comment (ajwad-shaikh) [inline Assets/Scripts/Mechanics/GameController.cs:66]: @cqvu clean ✨

**Review by cqvu — APPROVED** [review]
